### PR TITLE
Db setup

### PR DESCRIPTION
**Pull request by quinzel25**
Just basic model structure for trail table

### CODE REVIEW

**Comment by KJTempas** [comment]
I think you need to add import datetime at the top if you're using a date in the model
Do we need a dbconfig file? Maybe better so could swap out db types. then need to import that file at the top of this file
Should anything be unique? I'm not sure, just wondering

**Comment by quinzel25** [comment]
added import datetime and some basic functions to perform database tasks!

**Review by KJTempas — COMMENTED** [review]
after correction in delete all method, looks good

**Review by xd3262nd — APPROVED** [review]

**Comment by KJTempas** [comment]
look OK

**Review by KJTempas — COMMENTED** [review]
looks OK

**Review by KJTempas — APPROVED** [review]
looks OK

**Pull request merged**
